# Generated by Django 3.0.7 on 2021-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcommingevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
