# Generated by Django 3.0.7 on 2021-01-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0002_auto_20210109_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='city',
            new_name='injury',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_of_event',
            field=models.DateField(default='none'),
        ),
    ]
