# Generated by Django 3.0.7 on 2021-01-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0003_auto_20210113_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='msg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
