# Generated by Django 3.0.7 on 2021-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0005_auto_20210113_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
