# Generated by Django 3.0.7 on 2021-01-09 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('fathers_name', models.CharField(default='', max_length=20)),
                ('aadhar', models.IntegerField(default='0')),
                ('address', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('profile', models.ImageField(upload_to='yogbookingapp/images')),
                ('proffession', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('fathers_name', models.CharField(default='', max_length=20)),
                ('aadhar', models.IntegerField(default='0')),
                ('mobile', models.IntegerField(default=0)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('joblocation', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=20)),
                ('experiance', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('resume', models.FileField(upload_to='yogbookingapp/pdf')),
                ('profile', models.ImageField(default='', upload_to='yogbookingapp/images')),
                ('pic1', models.ImageField(default='', upload_to='yogbookingapp/images')),
                ('pic2', models.ImageField(default='', upload_to='yogbookingapp/images')),
                ('pic3', models.ImageField(default='', upload_to='yogbookingapp/images')),
                ('pic4', models.ImageField(default='', upload_to='yogbookingapp/images')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
