# Generated by Django 3.0.7 on 2021-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
