# Generated by Django 3.0.7 on 2021-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210115_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='pic1',
            field=models.ImageField(default='', upload_to='login/images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='pic2',
            field=models.ImageField(default='', upload_to='login/images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='pic3',
            field=models.ImageField(default='', upload_to='login/images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='pic4',
            field=models.ImageField(default='', upload_to='login/images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profile',
            field=models.ImageField(default='', upload_to='login/images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='resume',
            field=models.FileField(default='', upload_to='login/pdf'),
        ),
    ]
